import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/src/components/layout/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-screen h-screen" style={{
          boxShadow: "inset 0 0 20em 1em #919191;"
        }}>

          <Header />

          {children}

        </main>
      </body>
    </html>
  )
}
